services:
  ap-server:
    image: node:20
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"
    tty: true

  db-server:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: demo_db
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
